# Generated by Django 5.0.2 on 2024-02-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('pt', 'Português'), ('it', 'Italiano'), ('de', 'Deutsch')], default='en', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessagePT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.ManyToManyField(to='app_sender.emailrecipient')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessageES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.ManyToManyField(to='app_sender.emailrecipient')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessageEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.ManyToManyField(to='app_sender.emailrecipient')),
            ],
        ),
    ]
