# Generated by Django 5.0.2 on 2024-02-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessageen',
            name='category',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='emailmessagees',
            name='category',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='emailmessagept',
            name='category',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
